# Generated by Django 5.2 on 2025-04-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_chinmoy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chinmoy',
        ),
    ]
